# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CLgP6rMyxpwttkicEqmiB4nd32WYw7b0
"""

contacto = {
    "nombre": "julio escobar",
    "telefono": "964462429",
    "email": "jul.escobar@duocuc.cl",
    "edad": "47"
}

while True:
    print("\n--- MENÚ ---")
    print("1. Ver ficha")
    print("2. Editar dato")
    print("="*20)
    print("3. Salir")


    opcion = int(input("Seleccione una opción: "))

    if opcion == "1":

        print("\n--- FICHA DEL CONTACTO ---")
        for clave, valor in contacto.items():
            print(f"{clave.capitalize()}: {valor}")

    elif opcion == "2":

        print("\nCampos disponibles:", ", ".join(contacto.keys()))
        campo = input("Ingrese el campo que desea editar: ").lower()

        if campo in contacto:
            nuevo_valor = input(f"Ingrese el nuevo valor para {campo}: ")
            contacto[campo] = nuevo_valor
            print(f"{campo} actualizado correctamente.")
        else:
            print("Campo no válido.")

    elif opcion == "3":

        print("\n--- FICHA FINAL ---")
        for clave, valor in contacto.items():
            print(f"{clave.capitalize()}: {valor}")
        print("\nFin del programa.")
        break

    else:
        print("Opción inválida. Intente nuevamente.")